@URL = http://localhost:5216



###

GET {{URL}}/v1/usuario/4
Accept: application/json

###





POST {{URL}}/v1/usuario/cadastro
content-type: application/json

{
  "id": 9,
  "nome": "string",
  "email": "usuario666@email.com",
  "cpf": "25215311556",
  "senha": "string"
}

###
