@URL = http://localhost:5216



###
POST {{URL}}/v1/usuario/cadastro
content-type: application/json

{
  "id": 0,
  "nome": "string",
  "email": "usuariq0@email.com",
  "cpf": "20015310000",
  "senha": "string"
}
###



###
POST {{URL}}/v1/usuario/login
content-type: application/json

{
  "cpf": "90077570556",
  "senha": "string"
}
###



###
GET {{URL}}/v1/usuario/12
Accept: application/json
###




